In [1]:
import pandas as pd
import sys
from sklearn.decomposition import TruncatedSVD
import numpy as np

In [2]:
movies = pd.read_csv(r"..\data\processed\movies_clean.csv")
# ratings = pd.read_csv(r"..\data\processed\ratings_clean.csv")
ratings_small = pd.read_csv(r"..\data\raw\ratings_small.csv")

In [3]:
sys.path.append(r"..\src\models")   

from cb.content_based import (
    compute_tf_matrix,
    compute_cv_matrix,
    compute_truncatedSVD_matrix,
    recommend_movie
)

In [4]:
tf_matrix = compute_tf_matrix(movies)

In [5]:
# saving the tf matrix
from scipy.sparse import save_npz

save_npz(r"..\src\models\cb\tf_matrix.npz", tf_matrix)

In [6]:
tf_matrix.shape

(43416, 5000)

In [7]:
movies['title_lower'] = movies['original_title'].str.lower() # for case-insensitive matching

In [11]:
recommended_movies = recommend_movie(movies, "tangled", tf_matrix)

print("Recommended movies for Tangled\n")
top_movies = movies[movies['movieId'].isin(recommended_movies)][
        ["movieId", "original_title", "genres", "cast", "director"]
    ]

    # Keep the order the recommender gave
top_movies = top_movies.set_index("movieId").loc[recommended_movies].reset_index()
top_movies

Recommended movies for Tangled

,movieId,original_title,genres,cast,director
0,152916,Scene from the Elevator Ascending Eiffel Tower,['Documentary'],[],James H. White
1,132630,Tinker Bell and the Legend of the NeverBeast,"['Adventure', 'Animation', 'Family']","['Ginnifer Goodwin', 'Mae Whitman', 'Rosario D...",Steve Loter
2,144618,All Things Must Pass,['Documentary'],"['Dave Grohl', 'Elton John', 'Bruce Springsteen']",Colin Hanks
3,165959,Алеша Попович и Тугарин Змей,"['Animation', 'Comedy', 'Drama']","['Oleg Kulikovich', 'Lia Medvedeva', 'Dimitri ...",Konstantin Bronzit
4,7380,Ella Enchanted,"['Family', 'Fantasy', 'Comedy']","['Anne Hathaway', 'Hugh Dancy', 'Cary Elwes']",Tommy O'Haver
5,155283,Jack and the Beanstalk,"['Adventure', 'Animation', 'Fantasy']","['Jack Grimes', 'Corinne Orr', 'Billie Lou Watt']",Gisaburō Sugii
6,118997,Into the Woods,"['Fantasy', 'Comedy', 'Music']","['Meryl Streep', 'Emily Blunt', 'James Corden']",Rob Marshall
7,130800,Sleeping Beauty,"['Family', 'Fantasy']","['Tahnee Welch', 'Kenny Baker', 'Morgan Fairch...",David Irving
8,172793,Вовка в Тридевятом царстве,"['Adventure', 'Animation', 'Family', 'Fantasy']","['Rina Zelyonaya', 'Klara Rumyanova', 'Mikhail...",Boris Stepantsev
9,116833,Fehérlófia,"['Adventure', 'Animation', 'Fantasy']","['Cserhalmi György', 'Vera Pap', 'Gyula Szabó']",Marcell Jankovics

In [13]:
cv_matrix = compute_cv_matrix(movies)

In [14]:
recommended_movies = recommend_movie(movies, "Tangled", cv_matrix)

print("Recommended movies for Tangled\n")
top_movies = movies[movies['movieId'].isin(recommended_movies)][
        ["movieId", "original_title", "genres", "cast", "director"]
    ]

    # Keep the order the recommender gave
top_movies = top_movies.set_index("movieId").loc[recommended_movies].reset_index()
top_movies

Recommended movies for Tangled

,movieId,original_title,genres,cast,director
0,132630,Tinker Bell and the Legend of the NeverBeast,"['Adventure', 'Animation', 'Family']","['Ginnifer Goodwin', 'Mae Whitman', 'Rosario D...",Steve Loter
1,2096,Sleeping Beauty,"['Fantasy', 'Animation', 'Romance', 'Family']","['Mary Costa', 'Bill Shirley', 'Eleanor Audley']",Clyde Geronimi
2,155283,Jack and the Beanstalk,"['Adventure', 'Animation', 'Fantasy']","['Jack Grimes', 'Corinne Orr', 'Billie Lou Watt']",Gisaburō Sugii
3,172793,Вовка в Тридевятом царстве,"['Adventure', 'Animation', 'Family', 'Fantasy']","['Rina Zelyonaya', 'Klara Rumyanova', 'Mikhail...",Boris Stepantsev
4,4306,Shrek,"['Adventure', 'Animation', 'Comedy', 'Family',...","['Mike Myers', 'Eddie Murphy', 'Cameron Diaz']",Andrew Adamson
5,118997,Into the Woods,"['Fantasy', 'Comedy', 'Music']","['Meryl Streep', 'Emily Blunt', 'James Corden']",Rob Marshall
6,132632,Tinker Bell and the Pirate Fairy,"['Animation', 'Family']","['Mae Whitman', 'Christina Hendricks', 'Tom Hi...",Peggy Holmes
7,133137,Barbie: A Fairy Secret,"['Animation', 'Family', 'Fantasy']","['Diana Kaarina', 'Adrian Petriw', 'Cassandra ...",William Lau
8,114431,Les dents du singe,"['Animation', 'Comedy']",[],René Laloux
9,50149,Happily N'Ever After,"['Animation', 'Comedy', 'Family', 'Fantasy', '...","['George Carlin', 'Andy Dick', 'Sarah Michelle...",Yvette Kaplan

In [12]:
# reducing dimensionality with truncated SVD
reduced_matrix = compute_truncatedSVD_matrix(tf_matrix)

In [13]:
np.save(r"..\src\models\cb\reduced_matrix.npz", reduced_matrix)

In [ ]:
recommended_movies = recommend_movie(movies, "Harry Potter", tf_matrix) # very precise (like only Harry Potter movies)

print("Recommended movies for Harry Potter\n")
top_movies = movies[movies['movieId'].isin(recommended_movies)][
        ["movieId", "original_title", "genres", "cast", "director"]
    ]

    # Keep the order the recommender gave
top_movies = top_movies.set_index("movieId").loc[recommended_movies].reset_index()
top_movies

Recommended movies for Harry Potter

Harry Potter and the Goblet of Fire
Harry Potter and the Chamber of Secrets
Harry Potter and the Deathly Hallows: Part 2
Harry Potter and the Order of the Phoenix
Harry Potter and the Prisoner of Azkaban
Harry Potter and the Half-Blood Prince
Harry Potter and the Deathly Hallows: Part 1
Halloweentown
Shonen Sarutobi Sasuke
Wizards of Waverly Place: The Movie

In [ ]:
recommended_movies = recommend_movie(movies, "Harry Potter", reduced_matrix) # a bit more exploratory (include related fantasy worlds)

print("Recommended movies for Harry Potter\n")
top_movies = movies[movies['movieId'].isin(recommended_movies)][
        ["movieId", "original_title", "genres", "cast", "director"]
    ]

    # Keep the order the recommender gave
top_movies = top_movies.set_index("movieId").loc[recommended_movies].reset_index()
top_movies

Recommended movies for Harry Potter

Harry Potter and the Goblet of Fire
Harry Potter and the Chamber of Secrets
Alice in Wonderland
Harry Potter and the Deathly Hallows: Part 2
Eragon
Harry Potter and the Order of the Phoenix
Percy Jackson & the Olympians: The Lightning Thief
The Chronicles of Narnia: The Voyage of the Dawn Treader
Oz: The Great and Powerful
ゲド戦記

User Profile

In [16]:
sys.path.append(r"..\src\models")   

from cb.user_based import (
    explain_recommendation,
    recommend_unified
)

In [17]:
ratings_small.head(3)

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182

In [18]:
movies.head(3)

,genres,tmdbId,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,tagline,vote_average,vote_count,release_decade,keywords,cast,director,movieId,imdbId,metatags,title_lower
0,"['Animation', 'Comedy', 'Family']",862,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,['Pixar Animation Studios'],['United States of America'],unknown,7.7,5415.0,1990,"['jealousy', 'toy', 'boy', 'friendship', 'frie...","['Tom Hanks', 'Tim Allen', 'Don Rickles']",John Lasseter,1,114709,animation comedy family led by woody andys toy...,toy story
1,"['Adventure', 'Fantasy', 'Family']",8844,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"['TriStar Pictures', 'Teitler Film', 'Intersco...",['United States of America'],Roll the dice and unleash the excitement!,6.9,2413.0,1990,"['board game', 'disappearance', ""based on chil...","['Robin Williams', 'Jonathan Hyde', 'Kirsten D...",Joe Johnston,2,113497,adventure fantasy family when siblings judy an...,jumanji
2,"['Romance', 'Comedy']",15602,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.712900,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"['Warner Bros.', 'Lancaster Gate']",['United States of America'],Still Yelling. Still Fighting. Still Ready for...,6.5,92.0,1990,"['fishing', 'best friend', 'duringcreditssting...","['Walter Matthau', 'Jack Lemmon', 'Ann-Margret']",Howard Deutch,3,113228,romance comedy a family wedding reignites the ...,grumpier old men

In [19]:
movie_indices = pd.Series(movies.index, index=movies['tmdbId'])

In [20]:
user1 = ratings_small[ratings_small['userId'] == 1].merge(movies, on="movieId")
user1 = user1[user1['rating'] >= 3]
user1[["original_title", "genres", "cast", "director", "overview", "rating"]]

,original_title,genres,cast,director,overview,rating
1,Dumbo,"['Animation', 'Family']","['Sterling Holloway', 'Herman Bing', 'John McL...",Samuel Armstrong,Dumbo is a baby elephant born with oversized e...,3.0
2,Sleepers,"['Crime', 'Drama', 'Thriller']","['Robert De Niro', 'Brad Pitt', 'Kevin Bacon']",Barry Levinson,Two gangsters seek revenge on the state jail w...,3.0
4,Nuovo Cinema Paradiso,"['Drama', 'Romance']","['Philippe Noiret', 'Jacques Perrin', 'Marco L...",Giuseppe Tornatore,"A filmmaker recalls his childhood, when he fel...",4.0
8,Dracula,"['Romance', 'Horror']","['Gary Oldman', 'Winona Ryder', 'Anthony Hopki...",Francis Ford Coppola,When Dracula leaves the captive Jonathan Harke...,3.5
12,The French Connection,"['Action', 'Crime', 'Thriller']","['Gene Hackman', 'Fernando Rey', 'Roy Scheider']",William Friedkin,Tough narcotics detective 'Popeye' Doyle is in...,4.0
13,Tron,"['Science Fiction', 'Action', 'Adventure']","['Jeff Bridges', 'Bruce Boxleitner', 'David Wa...",Steven Lisberger,As Kevin Flynn searches for proof that he inve...,4.0
14,The Gods Must Be Crazy,"['Action', 'Comedy']","['N!xau', 'Michael Thys', 'Marius Weyers']",Jamie Uys,Misery is brought to a small group of Sho in t...,3.0
19,Blazing Saddles,"['Western', 'Comedy']","['Cleavon Little', 'Gene Wilder', 'Harvey Korm...",Mel Brooks,A town – where everyone seems to be named John...,3.0

In [21]:
movie_ids = movies['movieId'].values
movie_matrix = reduced_matrix # or movie_matrix_dense = tf_matrix.toarray()
movie_norms = np.linalg.norm(movie_matrix, axis=1)
content_index = pd.Index(movies['movieId'])

In [22]:
top_ids_user1 = recommend_unified(1, ratings_small, movies, movie_matrix, movie_ids, content_index, movie_norms)

In [23]:
top_movies_user1 = movies[movies['movieId'].isin(top_ids_user1)][['movieId','original_title','genres','cast','director']]
top_movies_user1 = top_movies_user1.set_index('movieId').loc[top_ids_user1].reset_index()

In [24]:
top_movies_user1

,movieId,original_title,genres,cast,director
0,26947,Pusher,"['Action', 'Crime', 'Drama', 'Thriller']","['Kim Bodnia', 'Mads Mikkelsen', 'Laura Drasbæk']",Nicolas Winding Refn
1,104837,Rage of Honor,"['Action', 'Thriller']","['Sho Kosugi', 'Lewis Van Bergen', 'Robin Evans']",Gordon Hessler
2,129749,La French,"['Action', 'Crime', 'Thriller']","['Jean Dujardin', 'Gilles Lellouche', 'Céline ...",Cédric Jimenez
3,113851,El niño,"['Action', 'Drama', 'Thriller']","['Luis Tosar', 'Jesús Castro', 'Eduard Fernánd...",Daniel Monzón
4,778,Trainspotting,"['Drama', 'Crime']","['Ewan McGregor', 'Ewen Bremner', 'Jonny Lee M...",Danny Boyle
5,109893,Chiko,['Drama'],"['Denis Moschitto', 'Volkan Özcan', 'Moritz Bl...",Özgür Yildirim
6,128882,Le marginal,"['Action', 'Crime', 'Drama', 'Thriller']","['Jean-Paul Belmondo', 'Henry Silva', 'Carlos ...",Jacques Deray
7,111360,Lucy,"['Action', 'Science Fiction']","['Scarlett Johansson', 'Morgan Freeman', 'Choi...",Luc Besson
8,122737,The Thirst,['Horror'],"['Matt Keeslar', 'Clare Kramer', 'Jeremy Sisto']",Jeremy Kasten
9,106996,Stakeout on Dope Street,['Crime'],"['Yale Wexler', 'Jonathan Haze', 'Steven Marlo']",Irvin Kershner

In [25]:
explain_recommendation(1, top_movies_user1, ratings_small, movies)

"shares genres: ['Action', 'Crime', 'Thriller']"

In [26]:
user2 = ratings_small[ratings_small['userId'] == 2].merge(movies, on="movieId")
user2 = user2[user2['rating'] >= 3]
user2[["original_title", "genres", "cast", "director", "overview", "rating"]]

,original_title,genres,cast,director,overview,rating
0,GoldenEye,"['Adventure', 'Action', 'Thriller']","['Pierce Brosnan', 'Sean Bean', 'Izabella Scor...",Martin Campbell,James Bond must unmask the mysterious head of ...,4.0
1,Sense and Sensibility,"['Drama', 'Romance']","['Kate Winslet', 'Emma Thompson', 'Hugh Grant']",Ang Lee,"Rich Mr. Dashwood dies, leaving his second wif...",5.0
2,Clueless,"['Comedy', 'Drama', 'Romance']","['Alicia Silverstone', 'Stacey Dash', 'Brittan...",Amy Heckerling,"Shallow, rich and socially successful Cher is ...",5.0
3,Se7en,"['Crime', 'Mystery', 'Thriller']","['Brad Pitt', 'Morgan Freeman', 'Gwyneth Paltr...",David Fincher,Two homicide detectives are on a desperate hun...,4.0
4,The Usual Suspects,"['Drama', 'Crime', 'Thriller']","['Stephen Baldwin', 'Gabriel Byrne', 'Chazz Pa...",Bryan Singer,"Held in an L.A. interrogation room, Verbal Kin...",4.0
...,...,...,...,...,...,...
70,Dances with Wolves,"['Adventure', 'Drama', 'Western']","['Kevin Costner', 'Mary McDonnell', 'Graham Gr...",Kevin Costner,"Wounded Civil War soldier, John Dunbar tries t...",5.0
71,Batman,"['Fantasy', 'Action']","['Jack Nicholson', 'Michael Keaton', 'Kim Basi...",Tim Burton,The Dark Knight of Gotham City begins his war ...,5.0
72,The Silence of the Lambs,"['Crime', 'Drama', 'Thriller']","['Jodie Foster', 'Anthony Hopkins', 'Scott Gle...",Jonathan Demme,"FBI trainee, Clarice Starling ventures into a ...",3.0
73,The Aristocats,"['Animation', 'Comedy', 'Family', 'Adventure']","['Phil Harris', 'Sterling Holloway', 'Scatman ...",Wolfgang Reitherman,When Madame Adelaide Bonfamille leaves her for...,3.0
74,James and the Giant Peach,"['Adventure', 'Animation', 'Family']","['Miriam Margolyes', 'Joanna Lumley', 'Pete Po...",Henry Selick,When the young orphan boy James spills a magic...,4.0

In [27]:
top_ids_user2 = recommend_unified(2, ratings_small, movies, movie_matrix, movie_ids, content_index, movie_norms)

In [28]:
top_movies_user2 = movies[movies['movieId'].isin(top_ids_user2)][['movieId','original_title','genres','cast','director']]
top_movies_user2 = top_movies_user2.set_index('movieId').loc[top_ids_user2].reset_index()

In [29]:
top_movies_user2

,movieId,original_title,genres,cast,director
0,163541,Gernika,"['Drama', 'War', 'Romance']","[""James D'Arcy"", 'María Valverde', 'Jack Daven...",Koldo Serra
1,26560,Tuntematon sotilas,"['Drama', 'War']","['Risto Tuorila', 'Pirkka-Pekka Petelius', 'Ka...",Rauni Mollberg
2,34536,The Great Raid,"['Action', 'History', 'War']","['Benjamin Bratt', 'James Franco', 'Connie Nie...",John Dahl
3,71779,Aces High,"['Action', 'Drama', 'War']","['Malcolm McDowell', 'Christopher Plummer', 'S...",Jack Gold
4,114367,Brother's War,"['Action', 'Drama']","['Tino Struckmann', 'Hugh Daly', 'Hayley Carr']",Jerry Buteyn
5,165279,El ángel de Budapest,"['War', 'Drama']","['Francis Lorenzo', 'Ana Fernández', 'János Bán']",Luis Oliveros
6,132883,Testament of Youth,"['History', 'Drama', 'War']","['Alicia Vikander', 'Kit Harington', 'Taron Eg...",James Kent
7,91707,In the Land of Blood and Honey,"['Drama', 'Romance', 'War']","['Zana Marjanović', 'Goran Kostić', 'Branko Đu...",Angelina Jolie
8,1222,Full Metal Jacket,"['Drama', 'War']","['Matthew Modine', 'Adam Baldwin', ""Vincent D'...",Stanley Kubrick
9,1233,Das Boot,"['Action', 'Drama', 'History', 'War', 'Adventu...","['Jürgen Prochnow', 'Herbert Grönemeyer', 'Kla...",Wolfgang Petersen

In [30]:
explain_recommendation(2, top_movies_user2, ratings_small, movies)

'similar themes'

In [31]:
# Cold-start with genres 
print("Cold start user, selected genres = ['Comedy', 'Adventure']:")
cold_start_example = recommend_unified(999, ratings_small, movies, reduced_matrix, movie_ids, movie_indices, movie_norms, n=5, selected_genres=['Comedy', 'Adventure'])

cold_start_example

Cold start user, selected genres = ['Comedy', 'Adventure']:

,original_title,genres,cast,director
22500,The Cat Concerto,"['Animation', 'Comedy']",[],Joseph Barbera
24120,Courage of Lassie,"['Family', 'Adventure', 'Drama']","['Elizabeth Taylor', 'Frank Morgan', 'Tom Drake']",Fred M. Wilcox
28533,Sex Appeal,['Comedy'],"['Louie Bonanno', 'Tally Chanel', 'Jerome Bren...",Chuck Vincent
24167,Drive Hard,"['Action', 'Comedy', 'Crime']","['Thomas Jane', 'John Cusack', 'Zoe Ventoura']",Brian Trenchard-Smith
19948,Stonehenge Apocalypse,"['Action', 'Adventure', 'Science Fiction', 'Th...","['Misha Collins', 'Torri Higginson', 'Peter Wi...",Paul Ziller